<?php

namespace BlogBundle\Repository;

/**
 * CommentResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentResponseRepository extends \Doctrine\ORM\EntityRepository
{
}
