<?php

namespace BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAuthorPosts($id)
    {
        return $this->createQueryBuilder('p')
            ->where('p.user = :id')
            ->setParameter('id', $id)
            ->orderBy('p.createdAt', 'DESC')
            ->getQuery()
            ->getResult()
            ;
    }

    public function getCategoryPosts($id)
    {
        return $this->createQueryBuilder('p')
            ->where('p.category = :id')
            ->setParameter('id', $id)
            ->orderBy('p.createdAt', 'DESC')
            ->getQuery()
            ->getResult()
            ;
    }

    public function getAllPosts()
    {
        return $this->createQueryBuilder('p')
            ->orderBy('p.createdAt', 'DESC')
            ->getQuery()
            ->getResult()
            ;
    }

    public function getPosts()
    {
        return $this->createQueryBuilder('p')
            ->orderBy('p.createdAt', 'DESC')
            ;
    }
}
